language: node_js
node_js:
   - "10"
branches:
    only:
       - master
cache:
  directories:
    - "node_modules"
before_script:
  - npm install -g @angular/cli
install:
  - npm install
script:
  - ng build --prod
notifications:
  slack: vdsg:YeRk6YBgJuTEtaRT1pPp76pb
  webhooks: 
    urls:
      - https://webhooks.gitter.im/e/205d430b653b44abcf8c
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
addons:
    apt:
      update: true
